version: "3.8"

services:
  # ------------- create a PostgreSQL container -----------------
  # docker run -d --name postgresDB -p 5432:5432
  # -e POSTGRES_DB=mytodo -e POSTGRES_PASSWORD=12345678
  # -e PGDATA=/var/lib/postgresql/data/pgdata
  # -v D:\workspace\cpe497\postgres-data:/var/lib/postgresql/data
  # postgres:15-alpine
  # -------------------------------------------------------------

  postgresdb:
    image: postgres:15-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=mytodo
      - POSTGRES_PASSWORD=12345678
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Database admin panel
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # --------------- create a Minio container --------------------
  # docker run -d -p 9000:9000 -p 9090:9090 --name minio
  # -v D:\workspace\cpe497\minio-data:/data
  # -e "MINIO_ROOT_USER=root" -e "MINIO_ROOT_PASSWORD=12345678"
  # quay.io/minio/minio server /data --console-address ":9090"
  # -------------------------------------------------------------

  minio1:
    image: quay.io/minio/minio:RELEASE.2023-09-07T02-05-02Z
    command: server --console-address :9001 /data{1...2}
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=12345678
      # - MINIO_OPTS="--console-address :9001"
      - MINIO_SERVER_URL=http://${MINIO_ADDR}:9000
      - MINIO_BROWSER_REDIRECT_URL=http://${MINIO_ADDR}:9001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${MINIO_ADDR}:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    hostname: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2

  # ----- Create Todo app container -------

  dome-todo:
    image: potikanond/dome-todo-photo
    restart: always
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:12345678@postgresdb:5432/mytodo
      - JWT_SECRET=PRISMA-MINIO-497
      - OBJ_STORAGE_ADDR=${MINIO_ADDR}
      - OBJ_STORAGE_PORT=9000
      - OBJ_ACCESS_KEY=Bd7RcGe3t5Ozf50rCNrQ
      - OBJ_SECRET_KEY=TZCVUMFHifEY76qbYPPRqbU20HQGxwrfoABID4nj
      - OBJ_BUCKET=todo-app

    deploy:
      # model: replicated # or global (one container/node)
      # replicas: 2
      # placement:
      #   max_replicas_per_node: 2

      resources:
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          cpus: "0.75"
          memory: 470M

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data1-1:
  data1-2:
  postgres-data:
